# Site settings
title: Breathe
email: breathe@thec3.uk
url: https://breathe.thec3.uk
description: "Breathe Ministries at C3"

# Color settings (hex-codes)
color:
  primary-dark: '#F9EACC'
  # primary-dark: '#F4E2BE'
  links: '#62892A'

# Footer settings
footer: Breathe
site-icon: icon-c3
map-center-lat: 52.200389
map-center-lng: 0.157216
 

site-map:
    home:
        title: home
        image: /img/0050.jpg
        inverse: true
        sections:
            - about
            - quote
            # - eventbrite
            - contact
            - map
        menu:
            - conferences
            - blog
            - other-events
    about:
        title: Welcome!
    eventbrite:
        title: Tickets
    contact:
        title: Contact
    map:
        title: Where?
    blog:
        title: Blog
        redirect: https://breatheconference.tumblr.com/
        # menu:
        #     - home
        #     - conferences
        #     - blog
        #     - other-events
    2017:
        title: 2017
        image: /img/0110.jpg
        inverse: true
        menu:
            - home
            - conferences
            - blog
            - other-events
    past:
        title: Past
        image: /img/2016-27.jpg
        inverse: true
        menu:
            - home
            - conferences
            - blog
            - other-events
    conferences:
        title: Conference
        submenu:
            - 2017
            - past
        menu:
            - home
            - conferences
            - blog
            - other-events
    other-events:
        title: Other Events
        image: /img/0079.jpg
        inverse: true
        menu:
            - home
            - conferences
            - blog
            - other-events


# Build settings
markdown: kramdown
permalink: pretty
theme: urban-static
