# Site settings
title: Breathe
email: breathe@thec3.uk
url: https://breathe.thec3.uk
baseurl: https://breathe.thec3.uk
description: "Breathe Ministries at C3"
share_image: /img/share.png
keywords: c3 cambridge breathe women ministries campbell angie conference church christian christians blessed brave eventbrite community speakers worship

# Footer settings
footer: Breathe
site-icon: icon-c3
map-center-lat: 52.200389
map-center-lng: 0.157216
 

site-map:
    home:
        title: home
        image: /img/0050.jpg
        inverse: true
        js: true
        sections:
            - about
            - quote-home
            # - eventbrite
            - contact
            - map
        menu:
            - conferences
            - blog
            - other-events
    about:
        title: Invite
    quote-home:
        title: quote
        image: /img/0100.jpg
    eventbrite:
        title: Tickets
    contact:
        title: Contact
    map:
        title: Where?
    blog:
        title: Blog
        path: blog
        # redirect: https://breatheconference.tumblr.com/
        # menu:
        #     - home
        #     - conferences
        #     - blog
        #     - other-events
    2017:
        title: 2017
        js: true
        image: /img/0110.jpg
        inverse: true
        menu:
            - home
            - conferences
            - blog
            - other-events
        sections:
            - map
    past:
        title: Past
        image: /img/2016-27.jpg
        inverse: true
        menu:
            - home
            - conferences
            - blog
            - other-events
    conferences:
        title: Conference
        submenu:
            - 2017
            - past
        menu:
            - home
            - conferences
            - blog
            - other-events
    other-events:
        title: Other Events
        js: true
        image: /img/0079.jpg
        inverse: true
        menu:
            - home
            - conferences
            - blog
            - other-events
        sections:
            - map


# Build settings
markdown: kramdown
permalink: pretty
theme: urban-static
include:
    - _redirects
    
gem:
    - jekyll-sitemap
